"""update

Revision ID: 6256956d332f
Revises: 734468b228c3
Create Date: 2024-09-08 16:23:52.605987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6256956d332f'
down_revision = '734468b228c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mock_iot_device', sa.Column('location', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mock_iot_device', 'location')
    # ### end Alembic commands ###
