"""Initial migration with devices, users, and logs update

Revision ID: 734468b228c3
Revises: 8f6599d9f2eb
Create Date: 2024-09-07 22:51:18.202013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '734468b228c3'
down_revision = '8f6599d9f2eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###
